// Sélections affichées en anglais. Voir le mode d'emploi dans src/lib/collections.ts.
import { THEMES, type BookRef, type Collection } from "./themes";

export const collections: Collection[] = [
  {
    id: "classiques",
    title: "The great classics",
    subtitle: "The essentials, to read at least once.",
    theme: THEMES.classiques,
    books: [
      { title: "Pride and Prejudice", author: "Jane Austen" },
      { title: "1984", author: "George Orwell" },
      { title: "To Kill a Mockingbird", author: "Harper Lee" },
      { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
      { title: "Jane Eyre", author: "Charlotte Brontë" },
      { title: "Moby-Dick", author: "Herman Melville" },
      { title: "Wuthering Heights", author: "Emily Brontë" },
      { title: "Great Expectations", author: "Charles Dickens" },
      { title: "The Catcher in the Rye", author: "J. D. Salinger" },
      { title: "One Hundred Years of Solitude", author: "Gabriel García Márquez" },
      { title: "Crime and Punishment", author: "Fyodor Dostoevsky" },
      { title: "The Little Prince", author: "Antoine de Saint-Exupéry" },
    ],
  },
  {
    id: "rentree",
    title: "Back to school",
    subtitle: "Campus novels, school memories and first times.",
    season: { from: "09-01", to: "10-15" },
    theme: THEMES.rentree,
    books: [
      { title: "The Secret History", author: "Donna Tartt" },
      { title: "Dead Poets Society", author: "N. H. Kleinbaum" },
      { title: "Harry Potter and the Philosopher's Stone", author: "J. K. Rowling" },
      { title: "Never Let Me Go", author: "Kazuo Ishiguro" },
      { title: "Matilda", author: "Roald Dahl" },
      { title: "The Catcher in the Rye", author: "J. D. Salinger" },
    ],
  },
  {
    id: "halloween",
    title: "Halloween chills",
    subtitle: "Best read with the lights on.",
    season: { from: "10-16", to: "11-02" },
    theme: THEMES.halloween,
    books: [
      { title: "Frankenstein", author: "Mary Shelley" },
      { title: "Dracula", author: "Bram Stoker" },
      { title: "The Shining", author: "Stephen King" },
      { title: "The Haunting of Hill House", author: "Shirley Jackson" },
      { title: "Rebecca", author: "Daphne du Maurier" },
      { title: "The Turn of the Screw", author: "Henry James" },
    ],
  },
  {
    id: "couette",
    title: "Cosy winter reads",
    subtitle: "Comfort books for long winter evenings under a blanket.",
    season: { from: "11-03", to: "02-28" },
    theme: THEMES.couette,
    books: [
      { title: "The Guernsey Literary and Potato Peel Pie Society", author: "Mary Ann Shaffer" },
      { title: "A Man Called Ove", author: "Fredrik Backman" },
      { title: "The House in the Cerulean Sea", author: "TJ Klune" },
      { title: "The Night Circus", author: "Erin Morgenstern" },
      { title: "Anne of Green Gables", author: "L. M. Montgomery" },
      { title: "The Hobbit", author: "J. R. R. Tolkien" },
      { title: "Jane Eyre", author: "Charlotte Brontë" },
    ],
  },
  {
    id: "noel",
    title: "Christmas reads",
    subtitle: "Stories that smell of pine needles and hot chocolate.",
    season: { from: "12-01", to: "12-31" },
    theme: THEMES.noel,
    books: [
      { title: "A Christmas Carol", author: "Charles Dickens" },
      { title: "Hercule Poirot's Christmas", author: "Agatha Christie" },
      { title: "Little Women", author: "Louisa May Alcott" },
      { title: "The Lion, the Witch and the Wardrobe", author: "C. S. Lewis" },
      { title: "The Polar Express", author: "Chris Van Allsburg" },
      { title: "The Nutcracker and the Mouse King", author: "E. T. A. Hoffmann" },
    ],
  },
  {
    id: "saint-valentin",
    title: "Love stories",
    subtitle: "For Valentine's Day, or any day of the year.",
    season: { from: "02-01", to: "02-15" },
    theme: THEMES.amour,
    books: [
      { title: "Romeo and Juliet", author: "William Shakespeare" },
      { title: "Pride and Prejudice", author: "Jane Austen" },
      { title: "Wuthering Heights", author: "Emily Brontë" },
      { title: "The Age of Innocence", author: "Edith Wharton" },
      { title: "Normal People", author: "Sally Rooney" },
      { title: "Me Before You", author: "Jojo Moyes" },
    ],
  },
  {
    id: "printemps",
    title: "Spring reads",
    subtitle: "Bright books for the return of sunny days.",
    season: { from: "03-01", to: "06-14" },
    theme: THEMES.printemps,
    books: [
      { title: "The Secret Garden", author: "Frances Hodgson Burnett" },
      { title: "The Elegance of the Hedgehog", author: "Muriel Barbery" },
      { title: "Where the Crawdads Sing", author: "Delia Owens" },
      { title: "Eat, Pray, Love", author: "Elizabeth Gilbert" },
      { title: "Chocolat", author: "Joanne Harris" },
      {
        title: "The Hundred-Year-Old Man Who Climbed Out of the Window and Disappeared",
        author: "Jonas Jonasson",
      },
    ],
  },
  {
    id: "plage",
    title: "Beach reads",
    subtitle: "Page-turners for toes in the sand.",
    season: { from: "06-15", to: "08-31" },
    theme: THEMES.plage,
    books: [
      { title: "My Brilliant Friend", author: "Elena Ferrante" },
      { title: "The Seven Husbands of Evelyn Hugo", author: "Taylor Jenkins Reid" },
      { title: "Big Little Lies", author: "Liane Moriarty" },
      { title: "And Then There Were None", author: "Agatha Christie" },
      { title: "The Truth About the Harry Quebert Affair", author: "Joël Dicker" },
      { title: "The Talented Mr. Ripley", author: "Patricia Highsmith" },
    ],
  },
];

// Dernières sorties : liste vide = recherche automatique des romans en anglais récents.
export const newReleases: BookRef[] = [];
