// Sélections affichées en espagnol. Voir le mode d'emploi dans src/lib/collections.ts.
import { THEMES, type BookRef, type Collection } from "./themes";

export const collections: Collection[] = [
  {
    id: "classiques",
    title: "Los grandes clásicos",
    subtitle: "Imprescindibles, para leer al menos una vez.",
    theme: THEMES.classiques,
    books: [
      { title: "Don Quijote de la Mancha", author: "Miguel de Cervantes" },
      { title: "Cien años de soledad", author: "Gabriel García Márquez" },
      { title: "Pedro Páramo", author: "Juan Rulfo" },
      { title: "La casa de los espíritus", author: "Isabel Allende" },
      { title: "Ficciones", author: "Jorge Luis Borges" },
      { title: "Rayuela", author: "Julio Cortázar" },
      { title: "La sombra del viento", author: "Carlos Ruiz Zafón" },
      { title: "La Regenta", author: "Leopoldo Alas Clarín" },
      { title: "Orgullo y prejuicio", author: "Jane Austen" },
      { title: "1984", author: "George Orwell" },
      { title: "Crimen y castigo", author: "Fiódor Dostoievski" },
      { title: "El principito", author: "Antoine de Saint-Exupéry" },
    ],
  },
  {
    id: "rentree",
    title: "Vuelta al cole",
    subtitle: "Mochilas, recuerdos de la escuela y primeras veces.",
    season: { from: "09-01", to: "10-15" },
    theme: THEMES.rentree,
    books: [
      { title: "Manolito Gafotas", author: "Elvira Lindo" },
      { title: "Nada", author: "Carmen Laforet" },
      { title: "El club de los poetas muertos", author: "N. H. Kleinbaum" },
      { title: "Harry Potter y la piedra filosofal", author: "J. K. Rowling" },
      { title: "El guardián entre el centeno", author: "J. D. Salinger" },
      { title: "Matilda", author: "Roald Dahl" },
    ],
  },
  {
    id: "halloween",
    title: "Noche de miedo",
    subtitle: "Para leer con la luz encendida.",
    season: { from: "10-16", to: "11-02" },
    theme: THEMES.halloween,
    books: [
      { title: "Frankenstein", author: "Mary Shelley" },
      { title: "Drácula", author: "Bram Stoker" },
      { title: "El resplandor", author: "Stephen King" },
      { title: "Rimas y leyendas", author: "Gustavo Adolfo Bécquer" },
      { title: "Rebeca", author: "Daphne du Maurier" },
      { title: "Otra vuelta de tuerca", author: "Henry James" },
    ],
  },
  {
    id: "couette",
    title: "Bajo la manta",
    subtitle: "Libros reconfortantes para las largas noches de invierno.",
    season: { from: "11-03", to: "02-28" },
    theme: THEMES.couette,
    books: [
      { title: "Como agua para chocolate", author: "Laura Esquivel" },
      {
        title: "La sociedad literaria y el pastel de piel de patata de Guernsey",
        author: "Mary Ann Shaffer",
      },
      { title: "Un hombre llamado Ove", author: "Fredrik Backman" },
      { title: "La tregua", author: "Mario Benedetti" },
      { title: "Jane Eyre", author: "Charlotte Brontë" },
      { title: "El hobbit", author: "J. R. R. Tolkien" },
    ],
  },
  {
    id: "noel",
    title: "Lecturas de Navidad",
    subtitle: "Historias que huelen a turrón y chocolate caliente.",
    season: { from: "12-01", to: "12-31" },
    theme: THEMES.noel,
    books: [
      { title: "Cuento de Navidad", author: "Charles Dickens" },
      { title: "Navidades trágicas", author: "Agatha Christie" },
      { title: "Mujercitas", author: "Louisa May Alcott" },
      { title: "El león, la bruja y el armario", author: "C. S. Lewis" },
      { title: "El Expreso Polar", author: "Chris Van Allsburg" },
      { title: "El cascanueces y el rey de los ratones", author: "E. T. A. Hoffmann" },
    ],
  },
  {
    id: "saint-valentin",
    title: "Historias de amor",
    subtitle: "Para San Valentín, o para todo el año.",
    season: { from: "02-01", to: "02-15" },
    theme: THEMES.amour,
    books: [
      { title: "El amor en los tiempos del cólera", author: "Gabriel García Márquez" },
      { title: "Veinte poemas de amor y una canción desesperada", author: "Pablo Neruda" },
      { title: "Romeo y Julieta", author: "William Shakespeare" },
      { title: "Cumbres borrascosas", author: "Emily Brontë" },
      { title: "La edad de la inocencia", author: "Edith Wharton" },
      { title: "Orgullo y prejuicio", author: "Jane Austen" },
    ],
  },
  {
    id: "printemps",
    title: "Lecturas de primavera",
    subtitle: "Libros luminosos para cuando vuelve el buen tiempo.",
    season: { from: "03-01", to: "06-14" },
    theme: THEMES.printemps,
    books: [
      { title: "Platero y yo", author: "Juan Ramón Jiménez" },
      { title: "El jardín secreto", author: "Frances Hodgson Burnett" },
      { title: "La elegancia del erizo", author: "Muriel Barbery" },
      { title: "Come, reza, ama", author: "Elizabeth Gilbert" },
      { title: "Chocolat", author: "Joanne Harris" },
      { title: "El abuelo que saltó por la ventana y se largó", author: "Jonas Jonasson" },
    ],
  },
  {
    id: "plage",
    title: "Lecturas de playa",
    subtitle: "Páginas que pasan solas, con los pies en la arena.",
    season: { from: "06-15", to: "08-31" },
    theme: THEMES.plage,
    books: [
      { title: "La amiga estupenda", author: "Elena Ferrante" },
      { title: "El tiempo entre costuras", author: "María Dueñas" },
      { title: "La verdad sobre el caso Harry Quebert", author: "Joël Dicker" },
      { title: "Y no quedó ninguno", author: "Agatha Christie" },
      { title: "Buenos días, tristeza", author: "Françoise Sagan" },
      { title: "El viejo y el mar", author: "Ernest Hemingway" },
    ],
  },
];

// Últimas novedades : liste vide = recherche automatique des romans en espagnol récents.
export const newReleases: BookRef[] = [];
